parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Infrastructure\Messenger\Middleware\UnroutableMessageLoggerMiddleware:
        tags: [ 'messenger.middleware' ]

    App\:
        resource: '../src/'

    Redis:
        factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
        arguments:
            - '%env(REDIS_URL)%'
