<?php

namespace App\Infrastructure\Command;

use Doctrine\DBAL\Connection;
use Redis;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name: 'app:audit:sync-to-postgres', description: 'Асинхронный перенос аудит-логов из Redis в PostgreSQL')]
class AuditSyncConsumerCommand extends Command
{
    public function __construct(
        private readonly Redis $redis,
        private readonly Connection $connection,
    )
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
