input {
  gelf { port => 5044 } # Принимаем логи в формате GELF от Docker
}

filter {
  # Если лог пришел от Symfony в формате JSON, парсим его на отдельные поля
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "symfony-logs-%{+YYYY.MM.dd}" # Каждый день — новый индекс
  }
}
